/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as contentRouteRouteImport } from './routes/(content)/route'
import { Route as contentIndexRouteImport } from './routes/(content)/index'
import { Route as contentPlaygroundRouteImport } from './routes/(content)/playground'
import { Route as contentSplatIndexRouteImport } from './routes/(content)/$/index'

const contentRouteRoute = contentRouteRouteImport.update({
  id: '/(content)',
  getParentRoute: () => rootRouteImport,
} as any)
const contentIndexRoute = contentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => contentRouteRoute,
} as any)
const contentPlaygroundRoute = contentPlaygroundRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => contentRouteRoute,
} as any)
const contentSplatIndexRoute = contentSplatIndexRouteImport.update({
  id: '/$/',
  path: '/$/',
  getParentRoute: () => contentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/playground': typeof contentPlaygroundRoute
  '/': typeof contentIndexRoute
  '/$/': typeof contentSplatIndexRoute
}
export interface FileRoutesByTo {
  '/playground': typeof contentPlaygroundRoute
  '/': typeof contentIndexRoute
  '/$': typeof contentSplatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(content)': typeof contentRouteRouteWithChildren
  '/(content)/playground': typeof contentPlaygroundRoute
  '/(content)/': typeof contentIndexRoute
  '/(content)/$/': typeof contentSplatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/playground' | '/' | '/$/'
  fileRoutesByTo: FileRoutesByTo
  to: '/playground' | '/' | '/$'
  id:
    | '__root__'
    | '/(content)'
    | '/(content)/playground'
    | '/(content)/'
    | '/(content)/$/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  contentRouteRoute: typeof contentRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(content)': {
      id: '/(content)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof contentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content)/': {
      id: '/(content)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof contentIndexRouteImport
      parentRoute: typeof contentRouteRoute
    }
    '/(content)/playground': {
      id: '/(content)/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof contentPlaygroundRouteImport
      parentRoute: typeof contentRouteRoute
    }
    '/(content)/$/': {
      id: '/(content)/$/'
      path: '/$'
      fullPath: '/$/'
      preLoaderRoute: typeof contentSplatIndexRouteImport
      parentRoute: typeof contentRouteRoute
    }
  }
}

interface contentRouteRouteChildren {
  contentPlaygroundRoute: typeof contentPlaygroundRoute
  contentIndexRoute: typeof contentIndexRoute
  contentSplatIndexRoute: typeof contentSplatIndexRoute
}

const contentRouteRouteChildren: contentRouteRouteChildren = {
  contentPlaygroundRoute: contentPlaygroundRoute,
  contentIndexRoute: contentIndexRoute,
  contentSplatIndexRoute: contentSplatIndexRoute,
}

const contentRouteRouteWithChildren = contentRouteRoute._addFileChildren(
  contentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  contentRouteRoute: contentRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
