/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as contentRouteRouteImport } from './routes/(content)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as contentSplatIndexRouteImport } from './routes/(content)/$/index'

const contentRouteRoute = contentRouteRouteImport.update({
  id: '/(content)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const contentSplatIndexRoute = contentSplatIndexRouteImport.update({
  id: '/$/',
  path: '/$/',
  getParentRoute: () => contentRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$/': typeof contentSplatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof contentSplatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(content)': typeof contentRouteRouteWithChildren
  '/(content)/$/': typeof contentSplatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$'
  id: '__root__' | '/' | '/(content)' | '/(content)/$/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  contentRouteRoute: typeof contentRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(content)': {
      id: '/(content)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof contentRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(content)/$/': {
      id: '/(content)/$/'
      path: '/$'
      fullPath: '/$/'
      preLoaderRoute: typeof contentSplatIndexRouteImport
      parentRoute: typeof contentRouteRoute
    }
  }
}

interface contentRouteRouteChildren {
  contentSplatIndexRoute: typeof contentSplatIndexRoute
}

const contentRouteRouteChildren: contentRouteRouteChildren = {
  contentSplatIndexRoute: contentSplatIndexRoute,
}

const contentRouteRouteWithChildren = contentRouteRoute._addFileChildren(
  contentRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  contentRouteRoute: contentRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
